import Sen_Gen as sg
import Connect_N as cn
Connect_N.add_link(sg.words["noun"]["pie"], sg.words["verb"]["to like"]) #adding words that are linked together. This will become easer later on
Connect_N.add_link(sg.words["verb"]["to like"], sg.words["verb"]["to eat"])
Connect_N.add_link(sg.words["noun"]["robin"], sg.words["noun"]["stick"], 2)
Connect_N.add_link(sg.words["noun"]["stick"], sg.words["noun"]["wood"])
Connect_N.add_link(sg.words["noun"]["wood"], sg.words["noun"]["water"], 2)
Connect_N.add_link(sg.words["verb"]["to eat"], sg.words["noun"]["corn"], 1.5)
Connect_N.add_link(sg.words["noun"]["rainstorm"], sg.words["noun"]["water"], 1.5)
Connect_N.add_link(sg.words["noun"]["sound"], sg.words["noun"]["rainstorm"])
Connect_N.add_link(sg.words["noun"]["song"], sg.words["noun"]["sound"])
Connect_N.add_link(sg.words["noun"]["horse"], sg.words["noun"]["rainstorm"])
Connect_N.add_link(sg.words["verb"]["to eat"], sg.words["noun"]["food"])
Connect_N.add_link(sg.words["noun"]["food"], sg.words["noun"]["pie"])
Connect_N.add_link(sg.words["noun"]["food"], sg.words["noun"]["cake"])
Connect_N.add_link(sg.words["noun"]["apple"], sg.words["noun"]["juice"])
Connect_N.add_link(sg.words["noun"]["apple"], sg.words["noun"]["banana"])
Connect_N.add_link(sg.words["noun"]["juice"], sg.words["noun"]["milk"], 3)
Connect_N.add_link(sg.words["noun"]["milk"], sg.words["noun"]["water"])
Connect_N.add_link(sg.words["noun"]["pear"], sg.words["noun"]["juice"], 2)
Connect_N.add_link(sg.words["noun"]["water"], sg.words["noun"]["bread"])
Connect_N.add_link(sg.words["noun"]["bread"], sg.words["noun"]["cake"], 1.5)
Connect_N.add_link(sg.words["noun"]["loaf"], sg.words["noun"]["bread"])
Connect_N.add_link(sg.words["noun"]["bread"], sg.words["noun"]["loaf"])
Connect_N.add_link(sg.words["noun"]["loaf"], sg.words["noun"]["corn"], 3)
Connect_N.add_link(sg.words["noun"]["robin"], sg.words["noun"]["song"], 1.5)
Connect_N.add_link(sg.words["noun"]["owl"], sg.words["noun"]["robin"], 2)
Connect_N.add_link(sg.words["noun"]["apple"], sg.words["noun"]["horse"], 1.25)
Connect_N.add_link(sg.words["verb"]["to eat"], sg.words["noun"]["apple"])
